### DISCUSSION TITLE
Announcing Podfetch with a preview Postgres deployment

### DISCUSSION THREAD

**Discussion by SamTV12345** [SamTV12345/PodFetch#144] [Announcements]
I am happy to share that PodFetch can now be used with a production grade database. You can try out the preview image with this docker-compose. Just copy the values from your existing PodFetch docker-compose and adapt the DATABASE_URL to below schema

```yaml
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:postgres
    ports:
      - "80:8000"
    volumes:
      - ./podcasts:/app/podcasts
    environment:
      - POLLING_INTERVAL=300
      - SERVER_URL=http://localhost:80
      - DATABASE_URL=postgresql://postgres:changeme@postgres/podfetch
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB:-podfetch}
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

volumes:
  postgres:

```
