### DISCUSSION TITLE
Help setting up Podfetch to work with AntennaPod

### DISCUSSION THREAD

**Discussion by gassssss** [SamTV12345/PodFetch#215] [Q&A] [answered]
Hi, I've tried the docker version got it to work with postgresql, loaded my ompl file, it loaded all of them and donwloaded the lastest podcast alright, so in the browser everything works fine, lovely. 

Most of the time I listen to podcasts while on the move and AntennaPod is my favorite app to do so, actually the main reason I found Podfetch was while trying to find a solution to seamlessly switch between my PC and mobile and just resume the playback. 

For some reason it doesn't seem to be working as I expected, maybe I'm wrong and that's not how it's supposed to work? I found [another discussion related to this issue](https://github.com/SamTV12345/PodFetch/discussions/141) that seems to say that once you are successfully logged into Podfetch gpoddersync and there are matching podcasts on both then they will sync but in my case that doesn't seem to happen, they share exactly the same feeds and on Podfetch end nothing seems to be affected.

Some more information about how I setup Podfectch, I created a second user that is not admin because it wouldn't let me login with the administrator one into the gpoddersync feature (as I understood I had to from another issue here on github because of basic auth ), maybe that's the problem?, that I have to login the web front end with that user? I'm logged in as admin but I don't see a logoff button... 

This is my compose file in case it's relevant:

```
  podfetch:
    image: samuel19982/podfetch:postgres
    container_name: podfetch
    user: ${UID:-1000}:${GID:-1000}
    environment:
      POLLING_INTERVAL: 60
      SERVER_URL: https://*****:*** # Adjust to your server url
      DATABASE_URL: 'postgresql://****' # https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
      DB_CONNECTIONS: 10 # optional
      BASIC_AUTH: true # Set to true if you want to use basic auth
      USERNAME: ***** # Username for basic auth
      PASSWORD: ***** # Password for basic auth      
      GPODDER_INTEGRATION_ENABLED: true
    volumes:
      - /opt/appdata/podfetch/podcasts:/app/podcasts
    ports: # Expuesto:Interno
      - 8001:8000
    restart: unless-stopped
```

Sorry if my question is an obvious one, I've been waiting a few weeks to see if anyone would have a similar question or issue. Unfortunately I fail to see the issue and some help would be lovely. 

Thanks a lot for your work, also love the new UI, thanks to everyone involved in that too.
