### DISCUSSION TITLE
Why does it when copying and pasting the url for SQLite dockercompose does docker not work correctly.

### DISCUSSION THREAD

**Discussion by 99powerbreaker** [SamTV12345/PodFetch#231] [Q&A]
When I copy and paste the docker compose 

```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "80:8000"
    volumes:
      - /home/####/podfetch-podcasts:/app/podcasts
      - /home/####/podfetch-db:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://localhost:80

volumes:
  podfetch-podcasts:
  podfetch-db:
```

  It causes the docker to not run the app. But when i take out "user: ${UID:-1000}:${GID:-1000}" Is this a bug or is this just something wrong on my end? I'm using portainer as a gui to host my docker images but just copy and pasted the docker compose? Or is there just common knowledge that you're supposed to replace the "user: ${UID:-1000}:${GID:-1000}" with something else.
