### DISCUSSION TITLE
Sync features via Gpodder API

### DISCUSSION THREAD

**Discussion by Deigue** [SamTV12345/PodFetch#280] [Q&A] [answered]
I followed the wiki instructions and setup a basic Antennapod Gpodder sync. Seems to work to the extent of being able to sync the elapsed timestamp over.

However, I am a bit confused. Is it not able to track the watch history and translate that over to PodFetch (i.e. mark episodes as watched, or favorited, or update the Home page so that the recently listened is the matching episode on Antennapod)

(Also I have added the podcast feeds manually, in case that was a pre-requisite to having the underlying episode informations updated and syncing two-ways)

For now it seems to sync the timestamp, and then if I go and manually find for the episode and click it, it will resume at that timestamp.
After finishing the episode on PodFetch, also didnt seem to mark the episode as watched/finished on PodFetch, and sync that information over.

I guess are these "to be implemented" features, or have I setup something drastically wrong?

**Comment by SamTV12345** [comment]
It should sync in both ways. So if you start listening something on your desktop and switch to phone and update the sync information it should show the new timestamp.

**Reply by Deigue** [reply]
I was able to get it to sync by going into the synchronization options and clicking "force full sync" ... shouldn't it be seamless even on the Antennapod side? Without having to go into the menu options every time you open up the app I mean.

As for the watched indicators, it seems like it is not implemented and the "UX improvement" discussion seems to allude to support these in the future. 
Additionally, I attempted a device to device sync and saw that current playing or recent playing along with favorited podcasts does not sync in this scenario either. Perhaps liked/favorited episodes might be out of scope, unless the Gpodder API supports this ... but Im sure there must be a way to pull up the most recently listened/updated episode and bring it up to the front of the UI to indicate that so-so is the current episode you are working on.

**Reply by SamTV12345** [reply, marked as answer]
Ah you mean the watch indicator in the podcast page. No that is not yet implemented but I am working on it. But you should be able to click on a podcast episode played with AntennaPod and resume from there. It is just not displayed to the end user yet.

**Reply by Deigue** [reply]
Thanks! that was my primary concern. Let me know if you know anything about the sync issue as well, I am ok with doing a force sync every time for now, but was expecting the intent was to be able to pick up the phone and automatically its synced.

**Comment by Deigue** [comment]
On another note, I have setup watchtower as suggested to update image to latest so I can keep getting updates. However, I do notice sometimes the Podfetch container goes down and I have to bring it up. Probably there is a reason behind it, but couldn't see anything abnormal in the console logs on docker. Is there anything I can provide to add more info/details about this in order to investigate why it is going down abruptly after a while?

**Reply by Deigue** [reply]
```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:postgres
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "80:8000"
    volumes:
      - ./podcasts:/app/podcasts
    environment:
      - POLLING_INTERVAL=300
      - SERVER_URL=http://***:80 # Adjust to your server url
      - DATABASE_URL=postgresql://postgres:changeme@postgres/podfetch
      - DB_CONNECTIONS=10 # optional
      - BASIC_AUTH=true
      - USERNAME=***
      - PASSWORD=***
      - GPODDER_INTEGRATION_ENABLED=true
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB:-podfetch}
    volumes:
      - postgres:/data/postgres
    restart: always
  watchtower:
    image: containrrr/watchtower
    restart: always
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_INCLUDE_RESTARTING: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  postgres:
  ```
  This is my `compose.yaml` ... I am new to working with docker compose, so I just recently read up documentation on how docker compose works and all the terminology around it.
