### DISCUSSION TITLE
Unable to sunc with antennapod

### DISCUSSION THREAD

**Discussion by Belettesoftware** [SamTV12345/PodFetch#779] [Q&A]
Well 
I have installed podfetch with docker, create a new user as admin and configure antenna pod to yncup with my instance: no error on connection.
I have several podcasts on my antenna pod app and just add another one podcast to podfetch.

When I make an sync, or a complete sync, nothing happens. There's no error displayed but podcatst are not sync.

Bellow my compose :
```yaml
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    user: ${UID:-998}:${GID:-100}
    ports:
      - "8005:8000"
    volumes:
      - /srv/dev-disk-by-uuid-6de92249-6b42-400f-9d7b-11d124a9c5e9/Audio/Podcasts:/app/podcasts:rw
      - /srv/dev-disk-by-uuid-6de92249-6b42-400f-9d7b-11d124a9c5e9/Config/Podfetch:/app/db:rw
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://192.168.1.10:8005
      - DATABASE_URL=sqlite:///app/db/podfetch.db
      - BASIC_AUTH=true
      - USERNAME=MYUSER
      - PASSWORD=USERPW
      - GPODDER_INTEGRATION_ENABLED=true
      - RUST_BACKTRACE=full
    networks:
      MyLocalNetwork:
        ipv4_address: "172.20.0.34"
        
networks:
  default:
    name: MyLocalNetwork
  MyLocalNetwork:
    external: true

volumes:
    podfetch-podcasts:
    podfetch-db:
```
Should I do something more ?
Thanks
