### DISCUSSION TITLE
Unable to synch in Antennapod

### DISCUSSION THREAD

**Discussion by shahram7** [SamTV12345/PodFetch#877] [Q&A]
hi everyone,
I hope you're doing well.
I'm getting the error 409 by trying to sync my antennapod app. :( 
I've deployed the PodFetch with this compose file:
```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    ports:
      - "80:8000"
    volumes:
      - /path/to/downloaded/podcasts:/app/podcasts
      - db:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=https://pod.mydomain.com
      - DATABASE_URL=sqlite:///app/db/podcast.db
      - BASIC_AUTH=true # Set to true if you want to use basic auth
      - USERNAME=username # Username for basic auth
      - PASSWORD=VeryStrongPassword123! # Password for basic auth      
      - GPODDER_INTEGRATION_ENABLED=true

volumes:
    db:
```
I have created a public hostname with cloudflare zero trust tunnel, now i have access to web-gui with https://pod.mydomain.com and as I have tried to sync in Antennapod i got this error 409. I've tried https://pod.mydomain.com/ and (pod.mydomain.com without https://) in both cases I got this error.

Can anyone help me with that?

Best Regards, Shahram
