### DISCUSSION TITLE
Help with OPML import not working.

### DISCUSSION THREAD

**Discussion by Ethanol6** [SamTV12345/PodFetch#939] [Q&A]
I've been trying to sort out an array of issues and it seems I've solved them all but created a new one.

Here's my docker-compose file perhaps there is an error here I can't see:

```
services:
  podfetch:
    restart: 'unless-stopped'
    image: samuel19982/podfetch:latest
    user: ${UID:-0}:${GID:-0}
    ports:
      - "9002:8000"
    volumes:
      - /mnt/diskA/sambashare/Podfetch:/app/podcasts
        #  podgrab-podcasts:/app/podcasts
      - podgrab-db:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://breakfast.lan:9002
      - DATABASE_URL=sqlite:///app/db/podcast.db
      - PODINDEX_API_KEY=XXXXX
      - PODINDEX_API_SECRET=XXXXXX
      - BASIC_AUTH=true
      - USERNAME=XXXXX
      - PASSWORD=XXXXX
volumes:
    podgrab-podcasts:
    podgrab-db:
```

I have an `admin` user created in the compose file and another `user` created through an invite in the Podfetch UI. 
The `user` is set as an uploader and can add podcasts individually from iTunes database but OPML import shows zero progress after several minutes.
The `admin` can add podcasts individually from iTunes database but OPML import also shows no progress after many minutes.

I noticed this when I was trying to find an easy way to move my podcast data to the new bind mount and thought I would just delete the podcasts and data from the UI and then re-add the subscriptions by importing an OPML. Only to find that OPML import isn't working.
