### ISSUE TITLE
No add podcast ( rss.xml )

### ISSUE THREAD

**Issue by Vctrsnts** [SamTV12345/PodFetch#1008]
### Describe the bug

Hi.
I install the last version with docker with the basic configuration:

```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    ports:
      - "3535:8000"
    volumes:
      - (directory_podcast):/app/podcasts
      - podfetch-db:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://localhost:3535
      - DATABASE_URL=sqlite:///app/db/podcast.db

volumes:
    podfetch-db:
```

Working and connect to web, but when I trying to add podcast ( xml ) all time connect with itunes. Is necessary this connection? Because I put the address to rss ( https://podcas.web_to_podcast/podcas.xml ) and the log of podfetch all time trying to connect with itunes. Why?

```
![podfetch_01](https://github.com/user-attachments/assets/23487440-f8b8-4e89-95f4-be8ebe6473ea)
```

Who add the podcast.xml

And I have a question. If I put podcast directly on directory to podcast, I watch and listen this podcast in podfetch web?

Thanks a lot

### Reproduction

Trying add rss.xml

### System Info

```Shell
System: debian stable
Browser: firefox
binaries: docker
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
