### ISSUE TITLE
unable to use podfetch properly

### ISSUE THREAD

**Issue by back-lacking** [SamTV12345/PodFetch#1252]
### Describe the bug

So I'm trying to get podfetch up and running (migrating from podgrab as its dead) and im having issues with getting podfetch working. 
In my browser console im getting 403 errors saying that i dont have access to those resources when putting it behind my traefik reverse proxy
![Image](https://github.com/user-attachments/assets/3989351b-3610-432c-9862-7b05331875ac)

trying to access the profile page just results in this 
![Image](https://github.com/user-attachments/assets/0184d4a3-48aa-447e-b82d-92fd4fdf4022)

below is my docker compose file
```yaml
version: "3.8"
services:
  podfetch:
    image: samuel19982/podfetch:latest
    container_name: podfetch
    environment:
      - POLLING_INTERVAL=60
      #- SERVER_URL=http://localhost:8000
      - SERVER_URL=https://podfetch.local.domain
      - DATABASE_URL=sqlite:///app/db/podcast.db
      - REVERSE_PROXY=true
      - REVERSE_PROXY_HEADER=X-FORWARDED-FOR
    volumes:
      - ./podfetch-db:/app/db
      - ./podcasts:/app/podcasts
    #ports:
      #- 8000:8000
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.podfetch-secure.entrypoints=websecure
      - traefik.http.routers.podfetch-secure.rule=Host(`podfetch.local.domain`)
      - traefik.http.routers.podfetch-secure.tls=true
      - traefik.http.routers.podfetch-secure.service=podfetch
      - traefik.http.services.podfetch.loadbalancer.server.port=8000
    restart: unless-stopped
networks:
  proxy:
    external: true
```

am i doing something wrong? 

### Reproduction

This assumes you have a traefik proxy setup. Use compose file provided

### System Info

```Shell
n/a
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
