### ISSUE TITLE
OIDC Doesn't Create a user in database

### ISSUE THREAD

**Issue by ch8zer** [SamTV12345/PodFetch#1257]
### Describe the bug

I'm starting with a fresh install (not using volumes as I intend to transition to PSQL. Volumes does not fix this bug.

Although I am able to sign in using OIDC (authentik), no users are created in the database. I manually queried the table and used the CLI to confirm this.

Here is my compose:

```yaml
version: '3'
services:
  podcasts:
    image: docker.io/samuel19982/podfetch:latest
    volumes:
      - /var/podcasts/downloads/:/app/podcasts
    environment:
      POLLING_INTERVAL: 60
      SERVER_URL: https://podcasts.DOMAIN
      DATABASE_URL: sqlite:///app/db/podcast.db
      GPODDER_INTEGRATION_ENABLED: "false"
      BASIC_AUTH: "false"
      OIDC_AUTH: "true"
      OIDC_CLIENT_ID: REDACTED
      OIDC_AUTHORITY: https://auth.DOMIAN//application/o/podcasts/
      OIDC_REDIRECT_URI: https://podcasts.DOMIAN//ui/login
      OIDC_SCOPE: openid profile email
      OIDC_JWKS: https://auth.DOMIAN//application/o/podcasts/jwks/
    labels:
      traefik.http.routers.podcasts.entrypoints: https
      traefik.http.routers.podcasts.rule: Host(`podcasts.DOMIAN/`)
      traefik.http.routers.podcasts.tls: true
      traefik.http.routers.podcasts.tls.certResolver: letsencrypt
      traefik.http.routers.podcasts.service: podcasts
      traefik.http.services.podcasts.loadbalancer.server.port: 8000
    network: proxy.network
```

When I navigate to `/ui/profile` I get:

```
Unexpected Application Error!
n is undefined
````

### Reproduction

see above

### System Info

```Shell
root@:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@:~# podman --version
podman version 5.4.1
```

### Used Package Manager

n/a

### Validations

- [x] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
