### ISSUE TITLE
Inconsistency with authentication types and strange behaviour

### ISSUE THREAD

**Issue by Chifilly** [SamTV12345/PodFetch#131]
### OIDC

When searching via Podcastindex, nothing happens, and checking the developer tools shows that it's returning a `401 Unauthorized` error for the URL `https://podfetch.domain.tld/api/v1/podcasts/1/search%20term/search`. When adding an RSS feed manually, the same thing happens.

I also notice that if I go to the `Administration` page, I can't access anything because I'm `not an administrator` but there's no information on how to set an administrator or anything.

### Basic Auth

When searching via Podcastindex, nothing happens, and checking the developer tools shows that it's returning a `502 Bad Gateway` error for the URL `https://podfetch.domain.tld/api/v1/podcasts/1/search%20term/search`. When adding an RSS feed manually, the same happens except it does actually add it (even though it appears nothing happens). Trying to delete it with files causes a `502` and nothing happens, deleting without files works fine, although it doesn't update the UI until refreshed.

The `Administration` page works fine for this type.

### No Auth

Essentially the same as Basic Auth but without the `Administration` page.

---

There doesn't seem to be any useful Docker logs so I'm not sure if I can find information anywhere as to what's happening.

### Reproduction

See below

### System Info

My compose file is as follows:

```yaml
services:
  podfetch:
    container_name: podfetch
    image: samuel19982/podfetch:latest
    networks:
      main:
    ports:
      - "4635:8000"
    volumes:
      - /media/nas/media/podcasts:/app/podcasts
      - ./volumes/podfetch/database:/app/db
    environment:
      POLLING_INTERVAL: 60
      SERVER_URL: https://podfetch.${DOMAIN}

      # BASIC_AUTH: true
      # USERNAME: username
      # PASSWORD: password

      # OIDC_AUTH: true
      # OIDC_AUTHORITY: https://auth.${DOMAIN}/application/o/podfetch/
      # OIDC_CLIENT_ID: client_id
      # OIDC_REDIRECT_URI: https://podfetch.${DOMAIN}/ui/login/
      # OIDC_SCOPE: openid profile email
      # OIDC_JWKS: https://auth.${DOMAIN}/application/o/podfetch/jwks/

      PODINDEX_API_KEY: podindex_key
      PODINDEX_API_SECRET: podindex_secret
    restart: unless-stopped

    labels:
      traefik.enable: true

      traefik.http.routers.podfetch.rule: HOST(`podfetch.${DOMAIN}`)
      traefik.http.routers.podfetch.entrypoints: https
      traefik.http.routers.podfetch.service: podfetch
      traefik.http.services.podfetch.loadbalancer.server.port: 8000
```
and obviously uncommenting/commenting the `BASIC_AUTH` and `OIDC_AUTH` blocks depending on what I want to enable

If there's any other info that'll be helpful, let me know

---

Also, the output of the command is as follows:
```
System:
    OS: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 629.38 MB / 15.58 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Firefox: 112.0.2
```

and that is on my server, with Docker version 20.10.17, build 100c701.

The browser I'm accessing PodFetch from is Firefox version 113.0.1

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
