### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by janaxhell** [SamTV12345/PodFetch#136]
### Describe the bug

I'm trying to deploy this on OMV6/Docker/Portainer.
I have used the docker-compose from home page and added auth and api [redacted], so that it now looks like this:

```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    ports:
      - "6666:8000"
    volumes:
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/podcasts:/app/podcasts
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Podfecth:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://192.168.1.94:6666
      - BASIC_AUTH: true
      - USERNAME: XXXXX
      - PASSWORD: XXXXX
      - PODINDEX_API_KEY: XXXXX
      - PODINDEX_API_SECRET: XXXXX
```

As soon as I deploy I get this error:

```
failed to deploy a stack: time="2023-05-21T09:25:45Z" 
level=warning msg="The \"CgSLq4cMC\" variable is not set. Defaulting to a blank string." time="2023-05-21T09:25:45Z" 
level=warning msg="The \"knd\" variable is not set. Defaulting to a blank string." services.podfetch.environment.2 must be a string
```

### Reproduction

Deploy the above compose

### System Info

```Shell
Open Media Vault 6
Docker
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
The issue is your Podindex API key. It contains a $. $ is interpreted by Docker. To prevent that add another $ in front/behind the other dollar sign.

**Comment by janaxhell** [comment]
There are in fact 2, but changing them to $$ still leads me to

`failed to deploy a stack: services.podfetch.environment.2 must be a string`

**Comment by Chifilly** [comment]
Your YAML syntax is incorrect in the environment variables. It should be as follows:
```yaml
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    ports:
      - "6666:8000"
    volumes:
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/podcasts:/app/podcasts
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Podfecth:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://192.168.1.94:6666
      - BASIC_AUTH=true
      - USERNAME=XXXXX
      - PASSWORD=XXXXX
      - PODINDEX_API_KEY=XXXXX
      - PODINDEX_API_SECRET=XXXXX
```

Arrays in YAML use `=` for value setting, and objects use `:`, and since you're using an array you need to replace the colons with equals signs

**Comment by janaxhell** [comment]
Ok, thanks again, but now with all variables replaces with = I get this new error:

`failed to deploy a stack: podfetch Pulling a7ca0d9ba68f Pulling fs layer fe5ca62666f0 Pulling fs layer b02a7525f878 Pulling fs layer fcb6f6d2c998 Pulling fs layer e8c73c638ae9 Pulling fs layer 1e3d9b7d1452 Pulling fs layer 4aa0ea1413d3 Pulling fs layer 7c881f9ab25e Pulling fs layer 5627a970d25e Pulling fs layer 96266735468f Pulling fs layer 80ec95682aee Pulling fs layer f51c8fa85103 Pulling fs layer dfc02eb7708f Pulling fs layer 52907d314ddc Pulling fs layer 4eec690774a4 Pulling fs layer 55ffd214c0e6 Pulling fs layer 11620ec24fb0 Pulling fs layer 3b8c74c5dade Pulling fs layer 4f4fb700ef54 Pulling fs layer 3a3a0eea33cc Pulling fs layer fcb6f6d2c998 Waiting f51c8fa85103 Waiting dfc02eb7708f Waiting 52907d314ddc Waiting 11620ec24fb0 Waiting 4eec690774a4 Waiting 55ffd214c0e6 Waiting 4f4fb700ef54 Waiting 3a3a0eea33cc Waiting 4aa0ea1413d3 Waiting e8c73c638ae9 Waiting 5627a970d25e Waiting 7c881f9ab25e Waiting 96266735468f Waiting 80ec95682aee Waiting a7ca0d9ba68f Downloading [&gt; ] 1.369kB/103.7kB fe5ca62666f0 Downloading [===&gt; ] 1.369kB/21.2kB fe5ca62666f0 Download complete a7ca0d9ba68f
`

**Comment by Chifilly** [comment]
I don't see any errors in that apart from `failed to deploy a stack`. Is there nothing else? That just seems like Docker pulling the layers for the image

**Comment by janaxhell** [comment]
All the errors appear in a quickly disappearing on-screen frame in Portainer (that I copy with mouse), since the image is not deployed, I don't know where to look for an error log.

**Comment by SamTV12345** [comment]
Maybe try again with docker-compose. I can't also see why it is failing. The container even didn't start.

**Comment by Chifilly** [comment]
Hmm, I'm not sure. I only use Portainer as a glorified container status and log viewer myself and do everything via the command line, so hopefully someone else has some insight. Maybe post your new compose file to double check everything, but I don't notice any issues in the original other than the colon stuff

In response to your edit, I believe there is a limit to 31 default networks since it seems the default networks are hard-coded. Maybe it's worth creating your own network(s) and assigning containers to them, since if you create your own it can assign a lot more IP addresses to them

As an example, here's the network I have all my media server containers assigned to:
```yaml
networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
```
and that will allow me to have 256 containers on that single network, and they can all communicate with each other

**Comment by janaxhell** [comment]
How did you choose 172.16.0.0? I'm rather new to selfhosting.
Also, when I create that, how do I assign my other containers? I just add those lines to my composes?

My Podfetch compose is exactly as above, except for ": " replaced with "="

**Comment by Chifilly** [comment]
It was just in an example I found forever ago and had no issues with it, so I've used it since. I'm pretty sure it can be anything that isn't already a used subnet. And in your compose file you add a `networks` key and the network name in an array or as an object. for example;
```yaml
services:
  podfetch:
    ...
    networks:
      - my_new_network
    ...
```
or
```yaml
services:
  podfetch:
    ...
    networks:
      my_new_network:
    ...
```
_I prefer the second option, so if I need to add specifics to the network configuration I can, which I had to do for some of my containers, but that's more advanced stuff you probably won't need to do_

They will then be assigned to all the networks under the `networks` key and can talk to each other with their container names. For example, some other container that's also on the `my_new_network` network could then use `http://podfetch:8000` to communicate with it, since as far as the containers are concerned, they're on the same LAN

**Comment by janaxhell** [comment]
Since I'm using Portainer to create it, for gateway and IP range, should I use my router IP? 
Like 
Subnet - 172.16.0.0/24
IPV4 Gateway - 192.168.1.1
IPV4 IP Range - 192.168.1.128/24
?

**Comment by Chifilly** [comment]
They aren't required. It's just if you want to be more specific with your network configuration for the containers. Docker should automatically assign those values

**Comment by janaxhell** [comment]
Eh, I'm almost there, but not quite: 
`failed to deploy a stack: services.networks must be a mapping`
My compose now looks like this and "omv1" is my network and shows as online

```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    ports:
      - "6666:8000"
    volumes:
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/podcasts:/app/podcasts
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Podfecth:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://192.168.1.94:6666
      - BASIC_AUTH=true
      - USERNAME=XXXXXXX
      - PASSWORD=XXXXXXX
      - PODINDEX_API_KEY=XXXXXXX
      - PODINDEX_API_SECRET=XXXXXXX
  networks:
    omv1
```

**Comment by Chifilly** [comment]
You need another indentation level on networks and the colon or hyphen was missing
```yaml
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    ports:
      - "6666:8000"
    volumes:
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/podcasts:/app/podcasts
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Podfecth:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://192.168.1.94:6666
      - BASIC_AUTH=true
      - USERNAME=XXXXXXX
      - PASSWORD=XXXXXXX
      - PODINDEX_API_KEY=XXXXXXX
      - PODINDEX_API_SECRET=XXXXXXX
    networks:
      omv1: # this line can either be "- omv1" or "omv1:"
````

**Comment by janaxhell** [comment]
Argh! Changed indentation and added semicolon, now: 
`failed to deploy a stack: service "podfetch" refers to undefined network omv1: invalid compose project `
but omv1 is there in the list of other networks. 
Maybe I should at least remove one?

**Comment by Chifilly** [comment]
I think I know the issue. The network was created outside the stack, but podfetch is inside the stack, and by default Docker prefixes anything inside the stack with the stack name. For example the network it will try and connect podfetch to if the stack was called `mystack` would be `mystack_omv1` which doesn't exist since you made it manually. Try adding the network within the stack with the above example snippet I posted, eg:

```yaml
services:
  podfetch:
    image: samuel19982/podfetch:latest
    ports:
      - "6666:8000"
    volumes:
      - /srv/dev-disk-by-uuid-2628F1C228F19153/data/media/podcasts:/app/podcasts
      - /srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Podfecth:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://192.168.1.94:6666
      - BASIC_AUTH=true
      - USERNAME=XXXXXXX
      - PASSWORD=XXXXXXX
      - PODINDEX_API_KEY=XXXXXXX
      - PODINDEX_API_SECRET=XXXXXXX
    networks:
      omv1: # this line can either be "- omv1" or "omv1:"

networks:
  omv1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
```
