### ISSUE TITLE
PodFetch crashes when starting fresh without a database

### ISSUE THREAD

**Issue by SamTV12345** [SamTV12345/PodFetch#14]
### Describe the bug

 Itried to start with a fresh directory for podfetch and I tried to copy over to old DB from podgrab. Nothing worked for me

I tried to open an issue in your repository, but it needs to much information, I use docker, not npm

```yaml
version: '3'
services:
  podgrabv2:
    image: samuel19982/podgrabv2:latest
    ports:
      - "9514:8000"
    volumes:
      - /medien/podcast:/app/podcasts
      - /docker/podfetch/podfetch.db:/app/podcast.db
    environment:
      - POLLING_INTERVAL=240
      - SERVER_URL=http://localhost
```

### Reproduction

Start above docker-compose

### System Info

```Shell
/
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
