### ISSUE TITLE
Cannot add podcasts - not admin nor uploader

### ISSUE THREAD

**Issue by tonwelle** [SamTV12345/PodFetch#230]
### Describe the bug

I have a fresh setup via docker compose but I cannot add any podcasts.
Webapp throws error: You are not admin nor uploader.
I have configured basic_auth to false.
When I reset and configure the container to use basic auth, I can indeed create an admin user in the user menu. Alas it only creates an invitation id I cannot use. Nothing happens whet i click the link button next to the id and I cannot enter it anywhere to accept the invite.

What is the expected behavior here as it’s nowhere in the docs how the invitation works.
And shouldn‘t the basic auth configured user be an admin by default?

thanks in advance for clarification 😉

### Reproduction

Create container via docker compose, postgres example. Open web Ui, try to add podcast.

### System Info

```Shell
N/A Using docker compose container.
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Which version do you use v4.0.1-5c3a3424 (HEAD)?

**Comment by tonwelle** [comment]
Thanks for replying.
Where can I find the version I am using? I pasted the Postgres compose example from the readme, adjusted it slightly and ran with it. It downloaded the _postgres_ tag docker image.

The docker compose i initially ran with is as follows: (passwords redacted back to "changeme") 
```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:postgres
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "8085:8000"
    volumes:
      - ./podcasts:/app/podcasts
    environment:
      - POLLING_INTERVAL=300
      - SERVER_URL=http://localhost:8085 # Adjust to your server url
      - DATABASE_URL=postgresql://postgres:changeme@postgres/podfetch
      - DB_CONNECTIONS=10 # optional
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB:-podfetch}
    volumes:
      - ./postgres:/data/postgres
    restart: unless-stopped

volumes:
  postgres:
```
