### ISSUE TITLE
AntennaPod: Unable to connect to Gpodder.net (code 404: Not Found)

### ISSUE THREAD

**Issue by realmain** [SamTV12345/PodFetch#240]
### Describe the bug

Version: `v4.0.1-16173cd2 (HEAD)`

Whenever I try to connect AntennaPod to my PodFetch instance, it keeps getting an error:

`Unable to connect to Gpodder.net (code 404: Not Found)`

Here is my docker compose:

```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:postgres
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "80:8000"
    volumes:
      - /var/lib/docker/volumes/podfetch/podcasts:/app/podcasts
    environment:
      - POLLING_INTERVAL=300
      - SERVER_URL=https://podcasts.mydomain.com # Adjust to your server url
      - DATABASE_URL=postgresql://postgres:<redacted>@postgres/podfetch
      - DB_CONNECTIONS=10 # optional
      - GPODDER_INTEGRATION_ENABLED:true
      - BASIC_AUTH=true
      - USERNAME=<redacted>
      - PASSWORD=<redacted>
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-<redacted>}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB:-podfetch}
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

volumes:
  postgres:
```

In **Nginx Proxy Manager**, I do have **Websockets Support** turned on. I also went into the CLI and tried creating another user and another admin to see if it worked, but same issue. I can access the website in a web browser at `https://podcasts.mydomain.com` without any issues.

In AntennaPod, I've tried setting the server address to these, but none of them worked:

* `https://podcasts.mydomain.com`
* `http://podcasts.mydomain.com`
* `podcasts.mydomain.com`

I have also tried the docker compose version with `image: samuel19982/podfetch:latest` to see if the Sqlite version would work, but had the same issue.

Maybe I am missing something?

### Reproduction

Create container via docker compose w/ postgres example with gpodder and basic auth on true

### System Info

```Shell
Proxmox -> LXC Container (Debian Template) -> Docker version 24.0.5, build ced0996
Proxmox -> VM (Debian) -> Docker version 24.0.5, build ced0996
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
