### ISSUE TITLE
Setting UID and GID not working

### ISSUE THREAD

**Issue by timosturm** [SamTV12345/PodFetch#261]
### Describe the bug

My goal is to use podfetch only for downloading podcasts. I want to manage them using nextcloud. The problem is, that the nextcloud user (33:33) does not have permission for the folders created by podfetch.

Therefore I tried to set the uid:gid in the podfetch compose.yml to match the nextcloud user. But running this fails as follows:

```
docker compose up
[+] Running 1/1
 ✔ Container podfetch-podfetch-1  Recreated                                                   0.7s
Attaching to podfetch-podfetch-1
podfetch-podfetch-1  | Debug file located at /home/rust/src/target/x86_64-unknown-linux-musl/release/build/podfetch-f510f74f070b1d4e/out/built.rs
podfetch-podfetch-1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Some("attempt to write a readonly database"))', src/main.rs:439:24
```

### Reproduction

```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    user: 33:33
    ports:
      - "8092:8000"
    volumes:
      - podcasts:/app/podcasts
      - podfetch-db:/app/db
    environment:
      - POLLING_INTERVAL=60
      - RUST_BACKTRACE=full

volumes:
  podcasts:
    name: "podcasts"
    external: true
  podfetch-db:
```

### System Info

```Shell
docker compose
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
