### ISSUE TITLE
Likely config error: Error(Some("Unable to open the database file"))'

### ISSUE THREAD

**Issue by markcs** [SamTV12345/PodFetch#277]
### Describe the bug

I'm trying to run PodFetch for the first time and use a local directory for the data storage.  My user UID/PID is 1000:1000.

This is the error I am seeing:
```
podfetch_1  | Debug file located at /home/rust/src/target/x86_64-unknown-linux-musl/release/build/podfetch-ef4b91b706960a1e/out/built.rs
podfetch_1  | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Some("Unable to open the database file"))', src/main.rs:439:24
podfetch_1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
podfetch_podfetch_1 exited with code 101
```

This is my docker-compose file:
```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    user: 1000:1000
    volumes:
      - /home/user/docker/podfetch/app:/app/podcasts
      - /home/user/docker/podfetch/db:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=https://url
```

### Reproduction

N/A

### System Info

```Shell
N/A
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
