### ISSUE TITLE
Gui/app broken - add podcasts, logout

### ISSUE THREAD

**Issue by peterpepo** [SamTV12345/PodFetch#356]
### Describe the bug

Issues:
1. Can't copy invite link - clipboard remains empty (Reproduce: login as admin, create invite link for user, try to copy it)
2. Can't add podcast from iTunes podcast (Reproduce: login as user -> all subscriptions -> Add new -> iTunes -> enter something e.g. 'atletika' -> loading circle goes on infinitely)
  - tried as pfadmin: finds podcast, click +, green snakebar "Podcast successfuly added", podcast is not added, container log 
```
thread 'tokio-runtime-worker' panicked at src/service/podcast_episode_service.rs:485:14:

called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("feed.podbean.com")), port: None, path: "/mozgovaatletika/feed.xml", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Try again" })) }

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'actix-rt|system:0|arbiter:3' panicked at src/service/rust_service.rs:192:22:

called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(322), ...)
```
3. Can't add podcast from rss (Add new -> RSS feed URL -> `https://feed.podbean.com/mozgovaatletika/feed.xml` -> Add) -> button doesn't work nothing happens
  - works as admin console log
```
Error during reqwest: error sending request for url (https://feed.podbean.com/mozgovaatletika/feed.xml): error trying to connect: dns error: failed to lookup address information: Try again
```
4. Can't import opml (tried to import my opml from antennapod), it got stuck at (also as admin)
`Progress: 0/12`
5. Can't log out (missing logout button, has to delete browsing data in order to login as different user)
6. Can't delete podcast

How to reproduce:
1. Build docker image
2. Add user docker `exec -it podfetch /app/podfetch/users add`, e.g. peter/password
3. Log into 192.168.2.40:8081 with new user peter/password

docker-compose.yml
```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:postgres
    container_name: podfetch
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "8081:8000"
    volumes:
      - /mnt/ds115j_rpi/docker/podfetch/podcasts:/app/podcasts
    environment:
      - POLLING_INTERVAL=300
      - SERVER_URL=http://192.168.2.40:8081 # Adjust to your server url
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeme}@podfetch-postgres/${POSTGRES_DB:-podfetch}
      - DB_CONNECTIONS=10 # optional
      - GPODDER_INTEGRATION_ENABLED=true
      - BASIC_AUTH=true
      - USERNAME=${PODFETCH_USR}
      - PASSWORD=${PODFETCH_USR_PASS}
    depends_on:
      - podfetch-postgres
  podfetch-postgres:
    image: postgres
    container_name: podfetch-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-podfetch}
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
```

.env
```
POSTGRES_USER="podfetch"
POSTGRES_PASSWORD="<myDbPwd>"
POSTGRES_DB="podfetch"
PODFETCH_USR="pfadmin"
PODFETCH_USR_PASS="<myAdminPwd>"
```

### Reproduction

Please see description.

### System Info

```Shell
https://hub.docker.com/layers/samuel19982/podfetch/postgres/images/sha256-aaf52b0bf1d093f864830db34dc3a90d04a7816497aeeea55fc4bdfa531abfd5?context=explore
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
