### ISSUE TITLE
Synchronisation between weboverview of PodFetch and AntennaPod does not work

### ISSUE THREAD

**Issue by update-freak** [SamTV12345/PodFetch#384]
### Describe the bug

I listened to a podcast in the web overview of the podfetch-instance and the podcast episode is marked as viewed in the overview but not in the AntennaPod-App.
I created an gpodder-Account with the command line with /app/podfetch users add.
In AntennaPod I'm logged in to this gpodder-Account and created the device name "Podcasts".
I'm wondering how I can select this device name "Podcasts" in the web overview of the podfetch-instance -> maybe that's the reason why the podcast episode is not marked as read in the AntennaPod-App?

![windows](https://github.com/SamTV12345/PodFetch/assets/40196995/5d62d90b-80d2-4987-8049-d15e4dadbccb)
![antennapod](https://github.com/SamTV12345/PodFetch/assets/40196995/06e04321-bf1e-4122-96fc-1bfc1b1e2247)

When I use the synchronisation between two Android-devices with AntennaPod and the gPodder-Account with the same device "Podcasts" the finished-listened podcasts are synchronised.

### Reproduction

1. create a gpodder-Account in Podfetch 2. Login to this account in AntennaPod 3. Add the podcasts from AntennaPod to PodFetch. 4. Finish a episode in PodFetch 5. Check if the episode is also finished in AntennaPod

### System Info

```Shell
Chrome: 119
AntennaPod: 3.1.2
PodFetch: 4.2.2
System: DSM 7.2.1 on Docker on Synology NAS
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
@update-freak Could you try the latest image and then run upon start `podfetch migration episodes`. This should hopefully resolve the issue with webview and app and vice versa.

**Comment by update-freak** [comment]
yes, watchtower updated to the latest-image and I tried with `podfetch migration episodes`. Then I restarted the container PodFetch and PodFetch-DB. Then I did a complete synchronisation on AntennaPod, but the podcast is in AntennaPod still not marked as finished.

**Comment by SamTV12345** [comment]
@update-freak Can you access the database and show the content of the episode table?

**Comment by update-freak** [comment]
How I can access to the database. Which tools are necessary?

**Comment by SamTV12345** [comment]
You can add this section to your docker-compose:

```
 pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  ```

and access the portal at http://<your-ip:8888 

There you need to add the postgres database with the credentials and then you can open tables and check the 'episodes' table

**Comment by update-freak** [comment]
I can not connect to the DB. I'm not sure what I did wrong. Maybe you see the mistake.

![2023-11-07 20_33_58-Portainer _ local](https://github.com/SamTV12345/PodFetch/assets/40196995/145c8bd9-5251-427d-a5e7-934e49d7c5f1)
![2023-11-07 20_33_38-pgAdmin 4](https://github.com/SamTV12345/PodFetch/assets/40196995/6f7f57da-57e3-4d3d-ab17-95988d7b57f0)
![2023-11-07 20_33_19-Portainer _ local](https://github.com/SamTV12345/PodFetch/assets/40196995/8e56de3e-8bb8-4f55-9452-65f79916324f)

**Comment by SamTV12345** [comment]
Try to change the hostname to postgres and the port to 5432. 

The problem with the hostname is that postgres doesn't communicate via http, so you only need the hostname, in your case the ip address of the docker machine. The other thing is the port number. Based on the docker-compose screenshot you haven't exposed the port 4135 to the host machine.

**Comment by update-freak** [comment]
tried with this config (also with hostname = postgres) but same result:

![2023-11-07 22_32_07-pgAdmin 4](https://github.com/SamTV12345/PodFetch/assets/40196995/a28c51ea-8b7f-41ce-b6af-a06b9bd0d6b0)

Full docker-compose is this one:
`
version: '3.9'
services:
  podfetch:
    image: samuel19982/podfetch:postgres
    container_name: PodFetch
    user: 1026:100
    ports:
      - 4135:8000
    volumes:
      - /volume1/docker/podfetch:/app/podcasts:rw
    environment:
      - POLLING_INTERVAL=300
      - SERVER_URL=https://podfetch.beispieladresse.dynv6.net
      - DATABASE_URL=postgresql://postgres:changeme@postgres/podfetch
      - BASIC_AUTH=true
      - USERNAME=Felix
      - PASSWORD=z1Pj!aszpy#fLe8n
      - GPODDER_INTEGRATION_ENABLED=true
    restart: always

  postgres:
    image: postgres
    container_name: PodFetch-DB
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "podfetch", "-U", "postgres"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: podfetch
    volumes:
      - /volume1/docker/podfetch/db:/var/lib/postgresql/data:rw
    restart: always
`

**Comment by SamTV12345** [comment]
I'll try it now.

**Comment by SamTV12345** [comment]
This was the config I meant:

<img width="705" alt="image" src="https://github.com/SamTV12345/PodFetch/assets/40429738/bc6655b2-de9d-4e50-9983-e3652b7b7ded">

**Comment by update-freak** [comment]
Any news on that. Please let me know if I can help

**Comment by SamTV12345** [comment]
> Any news on that. Please let me know if I can help

If you could send me a screenshot of the episodes table that would be dope.

**Comment by update-freak** [comment]
Tried it again, also with your proposal with several times with "postgres" but both cases did not work. I will try to ask in different forums to get an answer about that.
![2023-11-12 14_55_01-pgAdmin 4](https://github.com/SamTV12345/PodFetch/assets/40196995/70284cf6-3039-4387-ba03-b02623abe211)

**Comment by SamTV12345** [comment]
Weird. If everything is inside that docker-compose.yaml, it should work. I just tried it again. With hostname postgres it just works.


```yaml
version: '3.9'
services:
  podfetch:
    image: samuel19982/podfetch
    container_name: PodFetch
    user: 1026:100
    ports:
      - 4135:8000
    volumes:
      - /volume1/docker/podfetch:/app/podcasts:rw
    environment:
      - POLLING_INTERVAL=300
      - SERVER_URL=https://podfetch.beispieladresse.dynv6.net
      - DATABASE_URL=postgresql://postgres:changeme@postgres/podfetch
      - BASIC_AUTH=true
      - USERNAME=Felix
      - PASSWORD=z1Pj!aszpy#fLe8n
      - GPODDER_INTEGRATION_ENABLED=true
    restart: always

  postgres:
    image: postgres
    container_name: PodFetch-DB
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "podfetch", "-U", "postgres"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: podfetch
    volumes:
      - /volume1/docker/podfetch/db:/var/lib/postgresql/data:rw
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
 ```
