### ISSUE TITLE
401 Unauthorized on API GET

### ISSUE THREAD

**Issue by acbee** [SamTV12345/PodFetch#395]
### Describe the bug

I'm attempting to use PodFetch for the first time, using the latest Docker image, Postgres docker-compose file. 

When attempting to search iTunes for a podcast string ("serial"), browser is attempting to make a connection to http://192.168.0.1:8000/api/v1/podcasts/0/serial/search and receiving a 401 Unauthorized error. I've also attempted to add a RSS URL with similar results. 

I originally tried accessing PodFetch using Nginx reverse proxy (server.domain.com/podfetch) with the same issue, but am now attempting to use server IP and port. 

docker-compose.yaml (actual password has been replaced w/PASSWORD):

```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:postgres
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "8000:8000"
    environment:
      - POLLING_INTERVAL=300
      - SERVER_URL=http://192.168.0.1:8000
      - DATABASE_URL=postgresql://postgres:PASSWORD@postgres/podfetch
      - DB_CONNECTIONS=10
      - BASIC_AUTH=true
      - USERNAME=pfadmin
      - PASSWORD=PASSWORD
    volumes:
      - ./podcasts:/app/podcasts
    restart: unless-stopped

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB:-podfetch}
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

volumes:
  postgres:
```

### Reproduction

Use docker-compose.yaml above.

### System Info

```Shell
Version
v4.2.2-ec8a4924 (HEAD)

Commit
v4.2.2-ec8a4924 (HEAD)

CI build
No CI platform

Build date
Sun, 5 Nov 2023 20:33:24 +0000

Branch
HEAD

OS
linux
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
