### ISSUE TITLE
Episodes do not play when I click on the play button using latest docker image.

### ISSUE THREAD

**Issue by geomme** [SamTV12345/PodFetch#490]
### Describe the bug

**Describe the Bug** 
Episodes do not play when I click on the play button using latest docker image.

**Reproduction**

1.  Perform a fresh installation of the application using the latest image (v4.5.0-8f540e2). 
2.  Add a new podcast by searching on iTunes and clicking on the "+" button.
3.  Click on the play button of an episode.

**Observations**

-   In the browser's network tab, a GET request is made to `http://192.168.50.100:10001/api/v1/podcast/episode/198579ac-7812-4a6d-8c0d-c39f4920bd65` with a response code of 200 and a response content of `null`.

-   In the JavaScript console, the following error is logged:
```javascript
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'position') at EpisodeCard-c08Kf72Q.js:1:657
```

**YAML Configuration**
```yaml
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    user: 1000:1000
    ports:
      - "10001:8000"
    volumes:
      - /data/podfetch/podcasts:/app/podcasts
      - /data/podfetch/db:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://192.168.50.100:10001

volumes:
  podfetch-podcasts:
  podfetch-db:
```

**Additional Information**

-   The issue occurs with all podcasts, regardless of whether they are added from iTunes or imported via OPML.
-   Using the image `samuel19982/podfetch:v4.5.0-53d2ddd` instead of the latest version resolves the issue.

Thank you.

### Reproduction

.

### System Info

```Shell
.
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
