### ISSUE TITLE
Unable to access PodFetch RSS or system information page

### ISSUE THREAD

**Issue by SBCV-apegram** [SamTV12345/PodFetch#525]
### Describe the bug

On the podcast info page, when I click the link to access the PodFetch RSS feed, it takes me to a page that says 'Unauthorized'. No entry shows in the docker container logs.

A similar issue happens when making API calls (such as using the System Information page). Accessing the System Information has the additional symptom of throwing a 'IO extra error: Permission denied (os error 13) for path podcasts'  error in the docker container log. I've confirmed that the folder is owned by the correct user/group indicated in the docker compose file.

### Reproduction

Fresh install from latest docker image with GPodder and basic auth enabled using postgre and reverse proxy with websockets

### System Info

```Shell
Latest docker image running on Docker 20.10.23-1437 (DSM Container Manager). Host is a Synology DS720+ running DSM 7.2.1-69057 Update 3
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
You can login to PodFetch and refresh the API key. That way you get access to the RSS feeds.

**Comment by SBCV-apegram** [comment]
This did not solve my issue. I logged out, logged back in, and refreshed my API key.

I also redeployed with the latest image, still with the same issues.

Below is my docker compose file:
```
version: '3.9'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    container_name: PodFetch
    user: <user>:<group>
    ports:
      - 4135:8000
    volumes:
      - /volume1/docker/podfetch:/app/podcasts:rw
    environment:
      - POLLING_INTERVAL=300
      - SERVER_URL=https://<domain>
      - DATABASE_URL=postgresql://postgres:changeme@postgres/podfetch
      - GPODDER_INTEGRATION_ENABLED=true
      - BASIC_AUTH=true
      - USERNAME=<username>
      - PASSWORD=<password>
    restart: on-failure:5

  postgres:
    image: postgres
    container_name: PodFetch-DB
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "podfetch", "-U", "postgres"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: podfetch
    volumes:
      - /volume1/docker/podfetch/db:/var/lib/postgresql/data:rw
    restart: on-failure:5
```
