### ISSUE TITLE
Date remains in German despite language setting.

### ISSUE THREAD

**Issue by arcoast** [SamTV12345/PodFetch#53]
### Describe the bug

Using the latest docker image with the language set to `English`

```yaml
    podfetch:
        image: samuel19982/podgrabv2:latest
        container_name: podfetch
        ports:
            - 8005:8000
        volumes:
            - ${CONFIG}/podfetch/podcasts:/app/podcasts
            - ${CONFIG}/podfetch/db:/app/db
        environment:
            - POLLING_INTERVAL=60
            - SERVER_URL=http://10.146.0.1:8005
        restart: unless-stopped
```

![image](https://user-images.githubusercontent.com/81871508/230785319-41e10cdd-88a0-437e-837f-4d72a40c84f3.png)

`vor 3 Tagen` is displayed rather than `3 Days ago`, this is also the case if language is set to Français.

I checked https://github.com/SamTV12345/PodFetch/tree/main/ui/src/language/json but can't see the localisation translation for the error above.

### Reproduction

See above for docker-compose

### System Info

```Shell
Linux x64 host using 


Docker version 20.10.21, build baeda1f
```
```


### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
