### ISSUE TITLE
No audio on playback

### ISSUE THREAD

**Issue by ashprice** [SamTV12345/PodFetch#542]
### Describe the bug

Using Linux, 6.6.10-arch1-1, compose.yml as follows:

```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    user: ${UID:-0}:${GID:-0}
    ports:
      - "80:8000"
    depends_on:
      - postgres
    volumes:
      - ./podcasts:/app/podcasts
    environment:
      - POLLING_INTERVAL=300
      - SERVER_URL=http://localhost:80 # Adjust to your server url
      - DATABASE_URL=postgresql://postgres:changeme@postgres/podfetch
      - DB_CONNECTIONS=10 # optional
      - BASIC_AUTH=true
      - USERNAME=foo
      - PASSWORD=redacted
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB:-podfetch}
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

volumes:
  postgres:
```

Adding podcasts and downloading works as expected. Audio playback does not. 

No output whatsoever, except for the little 'pop' that headsets/speakers sometimes make when switching from 0 output to some output, only for the first file I try to play. My system audio indicates an output stream from the web UI as well, but I hear nothing. Other browser-based output streams work as expected. 

Files are downloaded fine, and the same files can be played with `mpv` by navigating to the directory. 

`docker-compose logs -f` doesn't show anything of interest. Not sure how else to debug, I tried exporting the contents of the docker image but didn't find the debug file mentioned in those logs (actually, the directory system was nothing like that, so I guess it's lack of knowledge about docker on my part.)

Please let me know what further information I can provide. 

### Reproduction

1. Be on linux. 2. Copy above compose.yml. 3. Download podcast. 4. Try to play in firefox. 

### System Info

```Shell
npx envinfo --system --binaries --browsers
Need to install the following packages:
envinfo@7.11.0
Ok to proceed? (y) y

  System:
    OS: Linux 6.6 Arch Linux
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 40.23 GB / 62.70 GB
    Container: Yes
    Shell: 3.7.0 - /bin/fish
  Binaries:
    Node: 21.5.0 - /usr/bin/node
    npm: 10.3.0 - /usr/bin/npm
  Browsers:
    Chromium: 120.0.6099.216
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
