### ISSUE TITLE
Invalid connection url for multiconnection

### ISSUE THREAD

**Issue by update-freak** [SamTV12345/PodFetch#727]
### Describe the bug

In Portainer I see this error messages in the log: Invalid connection url for multiconnection

![invalid](https://github.com/SamTV12345/PodFetch/assets/40196995/92c7b53a-fd12-4e4b-8e83-30f54ebe6837)

I installed it via docker compose
version: '3.9'
services:
  podfetch:
    image: samuel19982/podfetch:postgres
    container_name: PodFetch
    user: 1026:100
    ports:
      - 4135:8000
    volumes:
      - /volume1/docker/podfetch:/app/podcasts:rw
    environment:
      - POLLING_INTERVAL=300
      - SERVER_URL=https://podfetch.blabla.dynv6.net
      - DATABASE_URL=postgresql://postgres:changeme@postgres/podfetch
      - BASIC_AUTH=true
      - USERNAME=Felix
      - PASSWORD=PASSWORT
      - GPODDER_INTEGRATION_ENABLED=true
    restart: always

  postgres:
    image: postgres
    container_name: PodFetch-db
    security_opt:
      - no-new-privileges=true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "podfetch", "-U", "postgres"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: podfetch
    volumes:
      - /volume1/docker/podfetch/db:/var/lib/postgresql/data:rw
    restart: always

### Reproduction

1. Install via docker compose in Portainer 2. Check log

### System Info

```Shell
Synology NAS DSM 7.2
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Hi @update-freak. 

Please refer to the official docker-compose. You seem to be using the old tag postgres which was updated more than half a year ago. It seems like the database driver is too old for the current postgres version. The newer versions of PodFetch work without a problem :)


```yaml
services:
  podfetch:
    image: samuel19982/podfetch:latest
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "80:8000"
    volumes:
      - ./podcasts:/app/podcasts
    environment:
      - POLLING_INTERVAL=300
      - SERVER_URL=http://localhost:80
      - DATABASE_URL=postgresql://postgres:changeme@postgres/podfetch
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB:-podfetch}
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

volumes:
  postgres:
 ```
