### ISSUE TITLE
Subscription Empty and appears after config 

### ISSUE THREAD

**Issue by MrSiO** [SamTV12345/PodFetch#738]
### Describe the bug

(see video)
When I first open Podfetch from Android (tried Firefox, Chrome and Inconito) my subscription list appears empty.

Same thing happens on MacOS Safari & Chrome. 

I need to go to Setting/Manage Podcast (where I do see my subscription list) and only after that when I go back to Subscription, they appear... This fix will last until I close the browser tab. Have to do this everytime.

https://github.com/SamTV12345/PodFetch/assets/49870576/7b1d3a98-e6e1-4240-b74e-1d8840b45aaf

### Reproduction

Follow same steps as show on video using Android device on any browser

### System Info

```Shell
Unable to launch shell on Podfetch Docker container... Issue with image.

Using Docker-Compose in Ubuntu.
Intel NUC
Running version: v4.6.2-3b0758b7 (HEAD)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Maybe the configuration is wrong. Can you send me your configuration? Maybe also the Devtools responses in the network tab. Thanks :)

**Comment by MrSiO** [comment]
> Maybe the configuration is wrong. Can you send me your configuration? Maybe also the Devtools responses in the network tab. Thanks :)

Here is my Docker-Compose config

```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    container_name: podfetch
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "80:8000"
    volumes:
      - /home/user/podfetch_data/podcasts:/app/podcasts
      - /home/user/podfetch_data/db:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://192.168.107.134:80
      - DATABASE_URL=sqlite:///app/db/podcast.db
      - TELEGRAM_BOT_TOKEN=0123456789:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - TELEGRAM_BOT_CHAT_ID=-58xxxxxxxxxxx
      - TELEGRAM_API_ENABLED=true  
    restart: always    
      
    networks:
      VLAN-MEDIA:
        ipv4_address: 192.168.107.134

networks:
  VLAN-MEDIA:
    external: true

```    
    
 About the "Devtools" you are talking about, I have no such tabs anywhere....
 All I got at the top right is:
  
![podfetch-1](https://github.com/SamTV12345/PodFetch/assets/49870576/aef9c966-ac46-4076-9f17-102719f3a0ab)

Let me know how I can provide you with mode infos.

Thx alot!

**Comment by kronna** [comment]
I'm having the same issue exactly.

**Comment by SamTV12345** [comment]
> > Maybe the configuration is wrong. Can you send me your configuration? Maybe also the Devtools responses in the network tab. Thanks :)
> 
> Here is my Docker-Compose config
> 
> ```
> version: '3'
> services:
>   podfetch:
>     image: samuel19982/podfetch:latest
>     container_name: podfetch
>     user: ${UID:-1000}:${GID:-1000}
>     ports:
>       - "80:8000"
>     volumes:
>       - /home/user/podfetch_data/podcasts:/app/podcasts
>       - /home/user/podfetch_data/db:/app/db
>     environment:
>       - POLLING_INTERVAL=60
>       - SERVER_URL=http://192.168.107.134:80
>       - DATABASE_URL=sqlite:///app/db/podcast.db
>       - TELEGRAM_BOT_TOKEN=0123456789:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
>       - TELEGRAM_BOT_CHAT_ID=-58xxxxxxxxxxx
>       - TELEGRAM_API_ENABLED=true  
>     restart: always    
>       
>     networks:
>       VLAN-MEDIA:
>         ipv4_address: 192.168.107.134
> 
> networks:
>   VLAN-MEDIA:
>     external: true
> ```
> 
> About the "Devtools" you are talking about, I have no such tabs anywhere.... All I got at the top right is:
> 
> ![podfetch-1](https://private-user-images.githubusercontent.com/49870576/329881269-aef9c966-ac46-4076-9f17-102719f3a0ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MjcxNDQsIm5iZiI6MTcxNTYyNjg0NCwicGF0aCI6Ii80OTg3MDU3Ni8zMjk4ODEyNjktYWVmOWM5NjYtYWM0Ni00MDc2LTlmMTctMTAyNzE5ZjNhMGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE5MDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4N2IzM2JjN2I5NDIyMWQwYjFkNjIwMDQxOWI3OWMwMzFhODk0ZWU4YjI0ZTA0ODMyYmE1ZDc0NTczNDRmNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X80l6F2KOuoYYMinuMIckXBykrbhgBKrgtSRkQ1qGQE)
> 
> Note that "/home/user/podfetch_data/podcasts" is a mounted folder from a Synology NAS via SMB.
> 
> I also found that Podfech logs show this when I refresh the subscriptions that arent shown:
> 
> 2024-05-11T15:37:27 ❌ - Database error: disk I/O error 2024-05-12T23:02:47 ❌ - Database error: disk I/O error 2024-05-12T23:02:54 ❌ - Database error: disk I/O error
> 
> Then if I go to Settings/Manage podcast, then they show up (as seen in the video) but I still get those I/O error logs each time... HUmmmm
> 
> Let me know how I can provide you with mode infos but it does seem I have a DB issue....
> 
> Thx alot!

Does it work when you change the   line  `user: ${UID:-1000}:${GID:-1000}` to     
`user: ${UID:-0}:${GID:-0}?` @kronna @MrSiO

**Comment by MrSiO** [comment]
Yes!
That worked for me.

Is this a permanent fix or a workaround?

**Comment by SamTV12345** [comment]
> Yes!
> That worked for me.
> 
> So clearly an access right that ain't ok.
> 
> Since we don't wanna run this as Root (user 0) what would be a permanent fix?

Yes it is best practice to run the docker container not as root but docker always creates volumes as root. That is why this fixed the issue permanently.

**Comment by MrSiO** [comment]
Thx!

**Comment by kronna** [comment]
that works for me too, thank you.

**Comment by SamTV12345** [comment]
Great that this worked :). I have a documentation website with common pitfalls and installation instructions https://samtv12345.github.io/PodFetch/Installation.html#installation-with-docker-sqlite .

**Comment by MrSiO** [comment]
The info on that page still states UID:1000.
Might want to update the info for future reference.

Thx for your help and great project!

**Comment by 4lloyd** [comment]
I have the same problem when using SQLite. Changing the rights to the db folder won't solve the problem for me for some reason.

Part of my Docker Compose file:
```
services:
  podfetch:
    image: samuel19982/podfetch:latest
    container_name: podfetch
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "80:8000"
    volumes:
      - /test/data:/app/podcasts
      - /test/db:/app/db
```

I have run the following commands multiple times (also after the error):
```
sudo chown -R 1000:1000 /test
sudo chmod -R 777 /test
```

When I change the user to 0:0 in the Docker Compose file then the podcasts will show up. But I don't understand why this is the case as the folders seem to have enough permissions as far as I can see.

I did some further checks with user 1000:1000 configured in the Docker Compose file. The disk I/O error is caused by the following request, which is run when the "All Subscriptions" page is opened:
`/api/v1/podcasts/search?title=&order=ASC&orderOption=PUBLISHEDDATE&favoredOnly=false`

As a test I changed the request data and the following requests work without problems:
`/api/v1/podcasts/search?title=pd&order=ASC&orderOption=PUBLISHEDDATE&favoredOnly=false` (changed title)
`/api/v1/podcasts/search?title=&order=ASC&orderOption=PUBLISHEDDATE&favoredOnly=true` (changed favoredOnly)

When I use the search function on the "All Subscriptions" page and type in some letters (two or more), then the podcasts will start to show.

I find it strange that just in a specific case the search fails. If I manually search then soms results will show and therefore I suspect that the folder rights are ok. Do you maybe have any ideas if something else can cause this problem?

Let me know if you need more information and thank you for the work on this awesome app!
