### ISSUE TITLE
Downloads html instead of audio file

### ISSUE THREAD

**Issue by Ethanol6** [SamTV12345/PodFetch#82]
### Describe the bug

When clicking on the "i" icon next to an episode and selecting "Save to computer" the file downloaded is an html document, not the episode audio file. I presume this is why I cannot play an episode in the browser or stream an episode.

### Reproduction

Latest docker image

### System Info

```Shell
Server:
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 16.19 GB / 19.40 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 12.22.9 - /usr/bin/node
    npm: 8.5.1 - /usr/bin/npm

PC:
System:
    OS: Linux 5.4 Linux Mint 20.3 (Una)
    CPU: (8) x64 AMD FX(tm)-8350 Eight-Core Processor
    Memory: 2.67 GB / 23.43 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Firefox: 112.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamTV12345** [comment]
Download links should work again.

**Comment by Ethanol6** [comment]
```
version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    ports:
      - "9002:8000"
    volumes:
      - podgrab-podcasts:/app/podcasts
      - podgrab-db:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://<server IP>:9002
      - DATABASE_URL=sqlite:///app/db/podcast.db
      - PODINDEX_API_KEY=*****************
      - PODINDEX_API_SECRET=***************

volumes:
    podgrab-podcasts:
    podgrab-db:
```

Here's the docker-compose file I'm using. I have two podcasts added from the index and two podcasts added from iTunes. 

Only one of the podcasts will stream by clicking on the cloud.

If I click the "i" on an episode and click the floppy disc icon that episode now gets a play button. Clicking the play button shows the episode in the player but does not play anything. I understand the episode may still be downloading but after waiting for several minutes the episode still will not play. If I refresh the web page the episode will now play.

 If I select "Download to computer" (sometimes) a new tab opens and the episode plays in that tab. 

If I click the floppy disc icon, or the episode has been downloaded to my server automatically, and then choose "download to computer" my file manager opens and prompts me to save an html file.
