### ISSUE TITLE
no longer playing podcasts or displaying thumbnail images

### ISSUE THREAD

**Issue by SimonXIX** [SamTV12345/PodFetch#857]
### Describe the bug

I've been using PodFetch for a while running in Docker. Until a couple of weeks ago I was using the podfetch:postgres Docker image which recently disappeared so I switched to podfetch:latest. Although the application starts OK and connects to the Postgres database, the application no longer plays podcasts or displays thumbnail images for subscriptions (similar to https://github.com/SamTV12345/PodFetch/issues/823). 

<img width="715" alt="Screenshot 2024-07-29 at 14 33 29" src="https://github.com/user-attachments/assets/295fac5d-384b-42a0-8a94-2b1e03a30935">

When I click 'play' the word 'test' appears in the player bar and nothing else happens. There is nothing in the log to indicate anything wrong. 

This happens on my production server running Ubuntu 22.04.4 and Docker version 24.0.2 as well as on my testing MacBook running Sonama 14.5 with an Apple M1 chip and Docker 27.1.1.

Here's the full docker-compose.yml for the test version:

```
services:
  podfetch:
    image: samuel19982/podfetch:v4.5.0-c60dad5
    user: ${UID:-1726760676}:${GID:-84944165}
    ports:
      - "80:8000"
    volumes:
      - ./podcasts:/app/podcasts
    environment:
      - GPODDER_INTEGRATION_ENABLED=true
      - BASIC_AUTH=true
      - USERNAME=simonxix
      - PASSWORD=password
      - POLLING_INTERVAL=300
      - SERVER_URL=http://localhost:80
      - DATABASE_URL=postgresql://postgres:changeme@postgres/podfetch
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB:-podfetch}
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

volumes:
  postgres:

```

### Reproduction

reproduced on Ubuntu and on macOS

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 88.88 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 126.0.6478.185
    Safari: 17.5

System:
  OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  CPU: (2) x64 Intel Core Processor (Haswell, no TSX, IBRS)
  Memory: 60.37 MB / 949.67 MB
  Container: Yes
  Shell: 5.1.16 - /bin/bash
Binaries:
  Node: 12.22.9 - /usr/bin/node
  npm: 8.5.1 - /usr/bin/npm
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/SamTV12345/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/SamTV12345/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
